name: build pure-co storefront

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        run: actions/checkout@v3

      - name: enable corepack
        run: corepack enable

      - name: use node js and yarn
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'
