name: build pure-co storefront

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: enable corepack
        run: corepack enable

      - name: use node js and yarn
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: set up env variable
        run: echo "NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY }}" >> $GITHUB_ENV
          
      - name: install dependencies
        run: yarn install --immutable

      - name: build
        run: yarn build
